/* Generated by scripts/generate-classified-build-info.mjs. */
window.DocxtoolBuildInfo=Object.freeze({"build_id":"20260806014610-2398230cafe9","plugin_version":"1.1.1","build_timestamp":"2026-08-06T01:46:10.097Z","asset_hash":"2398230cafe9766b63c4b6e90534ca29417d553efe1d6d6c43ad4ef4dbaa63aa"});
if(typeof window.DocxtoolEarlyLog==="function"){window.DocxtoolEarlyLog("DEBUG","main","bootstrap.script.loaded","构建信息脚本已执行",{asset:"ui/build-info.js",build_id:window.DocxtoolBuildInfo.build_id});}
