/* Generated by scripts/generate-classified-build-info.mjs. */
window.DocxtoolBuildInfo=Object.freeze({"build_id":"20260807131555-93e3e449625a","plugin_version":"1.5.14","build_timestamp":"2026-08-07T13:15:55.258Z","asset_hash":"93e3e449625a3ad80747f991eb4372087ea6251c6301cd29e0a1bfd3c0bdc479"});
if(typeof window.DocxtoolEarlyLog==="function"){window.DocxtoolEarlyLog("DEBUG","main","bootstrap.script.loaded","构建信息脚本已执行",{asset:"ui/build-info.js",build_id:window.DocxtoolBuildInfo.build_id});}
