/* Generated by scripts/generate-classified-build-info.mjs. */
window.DocxtoolBuildInfo=Object.freeze({"build_id":"20260806073518-27919a7a6d8d","plugin_version":"1.3.2","build_timestamp":"2026-08-06T07:35:18.655Z","asset_hash":"27919a7a6d8da34d0920b9b9b7eea63f7b8d409dc9ca9e3c3b575ec5148d17e3"});
if(typeof window.DocxtoolEarlyLog==="function"){window.DocxtoolEarlyLog("DEBUG","main","bootstrap.script.loaded","构建信息脚本已执行",{asset:"ui/build-info.js",build_id:window.DocxtoolBuildInfo.build_id});}
